// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyGNkBrLrfAMi4wOnRC6h2LevHymYAh4',
    appId: '1:286140863746:web:a7912b1032cf0a96d2de1b',
    messagingSenderId: '286140863746',
    projectId: 'chatapp-298bf',
    authDomain: 'chatapp-298bf.firebaseapp.com',
    storageBucket: 'chatapp-298bf.appspot.com',
    measurementId: 'G-WH1HNWR96T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo35P3dmSdHcuoLxrpNJNWxbbpBMmaUXw',
    appId: '1:286140863746:android:c99554369a18cf10d2de1b',
    messagingSenderId: '286140863746',
    projectId: 'chatapp-298bf',
    storageBucket: 'chatapp-298bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfDyBPWK5OKjfj0KTrERU0W0iC-CB7cOU',
    appId: '1:286140863746:ios:f725f24d6ea7c727d2de1b',
    messagingSenderId: '286140863746',
    projectId: 'chatapp-298bf',
    storageBucket: 'chatapp-298bf.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfDyBPWK5OKjfj0KTrERU0W0iC-CB7cOU',
    appId: '1:286140863746:ios:1e66264d0d5c9afad2de1b',
    messagingSenderId: '286140863746',
    projectId: 'chatapp-298bf',
    storageBucket: 'chatapp-298bf.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
